[project]
name = "imagequantification101"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
jupyter = {cmd="jupyter lab"}

[dependencies]
python = "==3.11"
matplotlib = ">=3.8.4,<3.9"
scikit-image = ">=0.24.0,<0.25"
seaborn = ">=0.13.2,<0.14"
numpy = ">=1.26.4,<1.27"
napari = ">=0.4.19.post1,<0.4.20"
pyqt = ">=5.15.9,<5.16"
jupyter = ">=1.0.0,<1.1"
scikit-learn = ">=1.5.0,<1.6"

[pypi-dependencies]
napari-crop = "*"
napari-skimage = "*"
napari-skimage-regionprops = "*"
pyefd = "*"


[feature.nbdev.dependencies]
nbdev = ">=2.2.10,<2.3"

[feature.nbdev.tasks]
clean = "nbdev_clean --clear_all"

[environments]
nbdev = {features=["nbdev"], no-default-feature = true}
